In [4]:
import numpy as np
from numpy.linalg import svd

In [5]:
A = np.array([
    [1,-0.8],
    [0,1],
    [1,0]
])

In [6]:
print(A)

[[ 1.  -0.8]
 [ 0.   1. ]
 [ 1.   0. ]]


In [7]:
A.shape

(3, 2)

In [8]:
U, S, VT = svd(A,full_matrices=True)

In [9]:
print(U.shape,S.shape,VT.shape)

(3, 3) (2,) (2, 2)


In [10]:
U, S, VT = svd(A,full_matrices=False)

In [11]:
print(U.shape,S.shape,VT.shape)

(3, 2) (2,) (2, 2)


In [12]:
U

array([[-7.88170109e-01,  1.87057766e-16],
       [ 3.84473224e-01, -7.80868809e-01],
       [-4.80591530e-01, -6.24695048e-01]])

In [13]:
S

array([1.62480768, 1.        ])

In [14]:
VT

array([[-0.78086881,  0.62469505],
       [-0.62469505, -0.78086881]])

In [15]:
VT.T

array([[-0.78086881, -0.62469505],
       [ 0.62469505, -0.78086881]])